"""
Agent 5 — OutputGenerator
Converts enriched analysis into:
  1. Structured Markdown technical note
  2. Jira REST API v3 JSON payload (one issue per action item)
"""

import json
from datetime import datetime, timedelta


class OutputGenerator:

    def to_markdown(self, analysis: dict, metadata: dict) -> str:
        """Generate a structured Markdown technical note."""
        title = metadata.get("title", "Technical Session Notes")
        date = datetime.now().strftime("%Y-%m-%d")
        duration_min = metadata.get("duration_seconds", 0) // 60

        lines = [
            f"# {title}",
            f"",
            f"**Date:** {date}  |  **Duration:** {duration_min} min  |  **Source:** {metadata.get('source', 'unknown')}",
            f"",
        ]

        # Speakers
        speakers = analysis.get("speakers", [])
        if speakers:
            lines += [f"**Participants:** {', '.join(speakers)}", ""]

        # Executive Summary
        summary = analysis.get("summary", "")
        if summary:
            lines += [f"## 📋 Executive Summary", "", summary, ""]

        # Architectural Decisions
        decisions = analysis.get("decisions", [])
        if decisions:
            lines += ["## 🏗️ Architectural Decisions", ""]
            for d in decisions:
                impact_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(d.get("impact", "medium"), "⚪")
                lines += [
                    f"### {impact_emoji} [{d.get('timestamp', '??:??:??')}] {d.get('title', 'Decision')}",
                    f"",
                    f"**Decision:** {d.get('description', '')}",
                    f"",
                ]
                if d.get("rationale"):
                    lines += [f"**Rationale:** {d['rationale']}", ""]
                rejected = d.get("alternatives_rejected", [])
                if rejected:
                    lines += [f"**Alternatives rejected:** {', '.join(rejected)}", ""]
                lines.append("")

        # System Constraints
        constraints = analysis.get("constraints", [])
        if constraints:
            lines += ["## 🚧 System Constraints", ""]
            for c in constraints:
                type_emoji = {"performance": "⚡", "security": "🔐", "business": "💼", "technical": "⚙️"}.get(
                    c.get("type", "technical"), "📌")
                metric = f" — `{c['metric']}`" if c.get("metric") else ""
                lines += [
                    f"- {type_emoji} **[{c.get('timestamp', '')}]** {c.get('description', '')}{metric}",
                ]
            lines.append("")

        # Magic → System Transitions
        magic = analysis.get("magic_to_system", [])
        if magic:
            lines += ["## ✨ Magic → System Transitions", "",
                      "*These are the moments where vague statements became concrete technical specs.*", ""]
            for m in magic:
                lines += [
                    f"**[{m.get('timestamp', '')}]** `{m.get('component_affected', 'unknown')}`",
                    f"- 🌫️ **Vague:** \"{m.get('vague_statement', '')}\"",
                    f"- ⚙️  **Resolved:** {m.get('concrete_resolution', '')}",
                    "",
                ]

        # Action Items
        action_items = analysis.get("action_items", [])
        if action_items:
            lines += ["## ✅ Action Items", "",
                      "| Timestamp | Task | Owner | Deadline | Priority | Points |",
                      "|-----------|------|-------|----------|----------|--------|"]
            for a in action_items:
                priority_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(a.get("priority", "medium"), "⚪")
                lines.append(
                    f"| `{a.get('timestamp', '')}` "
                    f"| {a.get('task', '')} "
                    f"| @{a.get('owner', 'TBD')} "
                    f"| {a.get('deadline', 'TBD')} "
                    f"| {priority_emoji} {a.get('priority', 'medium')} "
                    f"| {a.get('jira_story_points', '?')} |"
                )
            lines.append("")

        # Key Concepts
        concepts = analysis.get("concepts", [])
        if concepts:
            lines += ["## 🧩 Key Concepts", ""]
            lines.append(", ".join(f"`{c}`" for c in concepts))
            lines.append("")

        lines += [
            "---",
            f"*Generated by Technical Video Intelligence Bot on {date}*"
        ]

        return "\n".join(lines)

    def to_jira_json(self, analysis: dict, metadata: dict) -> dict:
        """
        Generate Jira REST API v3 compatible JSON.
        Returns a dict with:
          - project_key: suggested Jira project key
          - issues: list of issue create payloads (POST /rest/api/3/issue)
          - bulk_payload: ready for POST /rest/api/3/issue/bulk
        """
        title = metadata.get("title", "Technical Session")
        # Suggest project key from title initials
        words = title.upper().split()
        project_key = "".join(w[0] for w in words if w.isalpha())[:4] or "TECH"

        issues = []
        action_items = analysis.get("action_items", [])

        for item in action_items:
            # Build description in Atlassian Document Format (ADF)
            description_text = (
                f"[{item.get('timestamp', '')}] From: {title}\n\n"
                f"{item.get('task', '')}\n\n"
            )
            if analysis.get("summary"):
                description_text += f"Context: {analysis['summary']}"

            issue = {
                "fields": {
                    "project": {"key": project_key},
                    "issuetype": {"name": item.get("jira_issue_type", "Task")},
                    "summary": item.get("task", "Action item from meeting"),
                    "description": {
                        "version": 1,
                        "type": "doc",
                        "content": [
                            {
                                "type": "paragraph",
                                "content": [{"type": "text", "text": description_text}]
                            }
                        ]
                    },
                    "priority": {
                        "name": item.get("priority", "medium").capitalize()
                    },
                    "labels": item.get("jira_labels", []),
                    "story_points": item.get("jira_story_points", 3),
                    # Assignee requires Jira account ID — placeholder here
                    # "assignee": {"accountId": "USER_ACCOUNT_ID"},
                }
            }

            # Add component if present
            component = item.get("jira_component")
            if component:
                issue["fields"]["components"] = [{"name": component}]

            # Add due date if parseable
            deadline = item.get("deadline", "")
            if deadline and deadline != "TBD":
                issue["fields"]["duedate"] = deadline

            issues.append(issue)

        # Also add one parent epic for the whole meeting
        if action_items:
            epic = {
                "fields": {
                    "project": {"key": project_key},
                    "issuetype": {"name": "Epic"},
                    "summary": f"[Video Intel] {title}",
                    "description": {
                        "version": 1,
                        "type": "doc",
                        "content": [{
                            "type": "paragraph",
                            "content": [{"type": "text", "text": analysis.get("summary", title)}]
                        }]
                    },
                    "labels": ["video-intel-bot", "auto-generated"],
                }
            }
            issues = [epic] + issues

        return {
            "project_key": project_key,
            "issues_count": len(issues),
            "issues": issues,
            "bulk_payload": {"issueUpdates": issues}
        }
